import type { StaticImageData } from "next/image";

import desk from "@/assets/office/desk.jpg";
import equipment from "@/assets/office/equipment.jpg";
import reception from "@/assets/office/reception.jpg";
import servicesWall from "@/assets/office/servicesWall.jpg";
import sign from "@/assets/office/sign.jpg";
import wide from "@/assets/office/wide.jpg";
import workstations from "@/assets/office/workstations.jpg";

/**
 * Crops of the Hotzonex office photo (img/office.png), generated by
 * `npm run brand`. Each shows a different part of the office so rows of cards
 * never repeat the same picture.
 */
export const officeImages = {
  reception,
  sign,
  servicesWall,
  equipment,
  workstations,
  desk,
  wide,
} satisfies Record<string, StaticImageData>;

export type OfficeImage = keyof typeof officeImages;

export const officeAlt: Record<OfficeImage, string> = {
  reception: "The Hotzonex office reception, with the Hotzonex IT Solution sign above the front desk",
  sign: "The Hotzonex IT Solution sign beside a screen reading “Fast. Secure. Reliable.”",
  servicesWall:
    "The services wall in the Hotzonex office, listing internet services, network installation, CCTV, computer repair and IT consultancy",
  equipment: "TP-Link and MikroTik networking equipment on display shelves in the Hotzonex office",
  workstations: "Computer workstations in the Hotzonex office",
  desk: "The Hotzonex front desk, with a scan-to-connect QR code on the counter",
  wide: "Inside the Hotzonex office: the services wall, equipment shelves, workstations and reception desk",
};
